// Generated by CoffeeScript 1.6.3
(function() {
  var App;

  Storage.prototype.setObj = function(key, obj) {
    return this.setItem(key, JSON.stringify(obj));
  };

  Storage.prototype.getObj = function(key) {
    return JSON.parse(this.getItem(key));
  };

  App = (function() {
    function App() {
      this.cacheElements();
      this.bindEvents();
    }

    App.prototype.cacheElements = function() {
      return this.$input = $('#new-todo');
    };

    App.prototype.bindEvents = function() {
      var _this = this;
      return this.$input.on('keyup', function(e) {
        return _this.create(e);
      });
    };

    App.prototype.create = function(e) {
      var randomId, val;
      val = $.trim(this.$input.val());
      if (!(e.which === 13 && val)) {
        return;
      }
      randomId = Math.round(Math.random() * 999999);
      localStorage.setObj(randomId, {
        id: randomId,
        title: val,
        completed: false
      });
      this.$input.val('');
      return this.displayItems();
    };

    App.prototype.displayItems = function() {
      return console.log("Displaying items");
    };

    return App;

  })();

  $(function() {
    var app;
    return app = new App;
  });

}).call(this);
